"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { exportDefinition } from "@/factory/storage";
import { TrackPresets, generateTrack, loadActiveTrack, loadTracks, saveTrack, type StoredTrack, type TrackConfig } from "@/factory/TrackFactory";

export function TrackStudio() {
  const [track, setTrack] = useState<StoredTrack>(TrackPresets[0]!); const [library, setLibrary] = useState<StoredTrack[]>([...TrackPresets]); const [status, setStatus] = useState("Circuito listo");
  useEffect(() => { let active = true; queueMicrotask(() => { if (active) { setTrack(loadActiveTrack()); setLibrary(loadTracks()); } }); return () => { active = false; }; }, []);
  const change = <K extends keyof TrackConfig>(key: K, value: TrackConfig[K]) => setTrack((current) => generateTrack({ ...current.config, [key]: value }));
  const points = track.definition.racingSpline.map((point) => `${50 + point.x * 1.18},${50 + point.z * 1.18}`).join(" ");
  const save = () => { setLibrary(saveTrack(track)); setStatus("Guardado y seleccionado para la próxima carrera"); };
  return <main className="track-shell"><header className="studio-topbar"><Link className="brand" href="/"><span className="brand-mark">PR</span><span>PRINT RUSH</span></Link><nav><Link href="/garage/character">PERSONAJE</Link><Link href="/garage/kart">KART</Link><Link href="/">JUGAR</Link></nav></header><section className="track-layout"><aside><span className="studio-kicker">CIRCUIT FACTORY V2</span><h1>TRAZA TU<br /><i>PISTA</i></h1><p>El spline genera asfalto, barreras, checkpoints, línea de carrera y puntos de recuperación automáticamente.</p><div className="studio-status"><span />{status}</div><details className="preset-library" open><summary>CIRCUITOS · {library.length}</summary>{library.map((item) => <div key={item.config.id}><button onClick={() => { setTrack(item); saveTrack(item); setStatus(`${item.config.name} equipado`); }}>{item.config.name}</button></div>)}</details></aside><section className="track-map"><svg viewBox="0 0 100 100" role="img" aria-label="Vista cenital del circuito"><polyline className="track-outer" points={points} /><polyline className="track-center" points={points} />{track.definition.checkpoints.map((point, index) => <circle key={index} cx={50 + point.x * 1.18} cy={50 + point.z * 1.18} r="1.2" />)}</svg><div><span>{track.config.theme}</span><strong>{track.config.name}</strong><small>SEED {track.config.seed}</small></div></section><aside className="track-controls"><label className="studio-control"><span>NOMBRE</span><input className="text-control" value={track.config.name} onChange={(event) => change("name", event.target.value)} /></label><TControl label="ANCHO" value={track.config.width} min={8} max={13} onChange={(value) => change("width", value)} /><TControl label="RADIO X" value={track.config.radiusX} min={20} max={36} onChange={(value) => change("radiusX", value)} /><TControl label="RADIO Z" value={track.config.radiusZ} min={14} max={27} onChange={(value) => change("radiusZ", value)} /><TControl label="COMPLEJIDAD" value={track.config.complexity} min={0} max={1} step={.01} onChange={(value) => change("complexity", value)} /><label className="studio-control"><span>TEMA</span><select value={track.config.theme} onChange={(event) => change("theme", event.target.value as TrackConfig["theme"])}><option>FLAGSHIP</option><option>WAREHOUSE</option><option>NEON_FACTORY</option></select></label><button className="random-button" onClick={() => setTrack(generateTrack({ ...track.config, id: `track-${Date.now().toString(36)}`, seed: Date.now() >>> 0, name: "Generated Rush" }))}>↻ REGENERAR SEMILLA</button><div className="drawer-actions"><button className="drawer-primary" onClick={save}>GUARDAR + USAR</button><button onClick={() => exportDefinition(`${track.config.id}.json`, track)}>EXPORTAR</button></div></aside></section></main>;
}
function TControl({ label, value, min, max, step = .1, onChange }: { label: string; value: number; min: number; max: number; step?: number; onChange: (value: number) => void }) { return <label className="studio-control"><span>{label}<b>{value.toFixed(step < .1 ? 2 : 1)}</b></span><input type="range" min={min} max={max} step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} /></label>; }
